enabled: true
dryRun: false

# Reference to YAML file in the same repository
# as this config file
gitHubResources: github-resources.yml

# Add users from the specified source team as collaborators
# to the repository containing this file.
collaboratorSync:
  role: push
  source: commonhaus-test/team-quorum-default
  logins:
    - ejamison3
  # ignore the presence/absence of these logins
  ignoreUsers:
    - botLogin

emailNotifications:
  errors:
    - test@commonhaus.org
  dryRun:
    - test@commonhaus.org
  audit:
    - test@commonhaus.org
